package com.qabas.app

import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue

object Translator {
    var currentLanguage by mutableStateOf("ar")
    
    fun setLanguage(lang: String) {
        currentLanguage = lang
    }

    private val dictionaryEn = mapOf(
        "موقف مؤثر من حياة الصحابة..." to "An influential position on the lives of the Companions...",
        "الإعدادات" to "Settings",
        "إلغاء المعالجة" to "Cancel processing",
        "عام" to "general",
        "عادي" to "normal",
        "خاشع وهادئ" to "Submissive and quiet",
        "متغير (B) - خطاف 2" to "Variable (B) - Hook 2",
        "الرؤية السينمائية" to "Cinematic vision",
        "حفظ" to "keep",
        "إعادة التوليد" to "Regeneration",
        "تم الإنتاج بأسلوب:" to "Produced in style:",
        "الفكرة الأساسية" to "Basic idea",
        "اختبار A/B" to "A/B testing",
        "أزرق" to "blue",
        "ترتيل وتجويد" to "Intonation and intonation",
        "الرؤية الإخراجية" to "Directing vision",
        "بذيء" to "saucy",
        "المؤثرات المحيطية (Ambient FX):" to "Ambient FX:",
        "فكرة تحفيزية." to "Motivational idea.",
        "الرصيد المتبقي" to "Remaining balance",
        "صورة" to "image",
        "[INFO] جاري تحميل الأصول والمؤثرات الصوتية..." to "[INFO] Loading assets and sound effects...",
        "مشروع جديد" to "New project",
        "هادئ ومريح" to "Quiet and relaxing",
        "جودة التوليد الافتراضية" to "Default generation quality",
        "المخرج الذكي بين يديك. ماذا سنصنع اليوم؟" to "The smart outlet is in your hands. What will we do today?",
        "رياح وصحراء" to "Wind and desert",
        "4. الصور المولدة تُطمس وجوهها، بينما الصور الحقيقية تبقى كما هي." to "4. Generated images blur their faces, while real images remain as they are.",
        "فشل الاتصال بالخادم. جاري استخدام المحاكي." to "Failed to connect to the server. Using the emulator.",
        "16:9 (يوتيوب)" to "16:9 (YouTube)",
        "إضافة نص أو صوت في أول 3 ثواني لجذب الانتباه." to "Add text or sound in the first 3 seconds to grab attention.",
        "الصوتيات" to "Acoustics",
        "تحفيزي" to "Motivational",
        "جاري تحضير السيناريو..." to "Script being prepared...",
        "الخيارات المتقدمة" to "Advanced options",
        "رفع مستند" to "Document fix",
        "موافق" to "agree",
        "تهيئة محرك الريندر Qabas Engine v2.4..." to "Configuring the renderer engine Qabas Engine v2.4...",
        "مبيعات (Conversion)" to "Sales",
        "نشاط" to "activity",
        "حذف" to "remove",
        "إيقاعي" to "rhythmic",
        "الألوان السائدة" to "Predominant colours",
        "تأملية هادئة" to "Quiet contemplation",
        "نيون" to "neon",
        "لحن" to "the tone",
        "معدل البت (Bitrate)" to "Bitrate",
        "مدة الفيديو التقريبية:" to "Approximate video duration:",
        "تطبيق التغييرات (إعادة التوليد)" to "Apply changes (regeneration)",
        "الجو العام (Tone):" to "General atmosphere (Tone):",
        "حماسي" to "enthusiastic",
        "حزين ومؤثر" to "Sad and poignant",
        "العودة للرئيسية" to "Back to main page",
        "تراكب CTA" to "CTA overlay",
        "رسمي" to "official",
        "الحرارة" to "the heat",
        "قصة" to "story",
        "مدة الفيديو: \\videoDuration" to "Video Duration: \\videoDuration",
        "أناشيد بدون موسيقى" to "Chants without music",
        "تلاشي" to "searching",
        "أو اختر بطاقة شحن (اختياري)" to "Or choose a shipping card (optional)",
        "نوع الانتقالات" to "Transfer type",
        "إطارات رئيسية (Keyframes)" to "Keyframes",
        "وثائقي سينمائي" to "Cinematic documentary",
        "استخراج ذكي من فيديو" to "Intelligent extraction from video",
        "محيطي" to "environmental",
        "ملحمي" to "epic",
        "إنشاء مشروع سينمائي جديد" to "Create a new cinematic project",
        "تكبير" to "Zoom in",
        "نسبة التفاعل" to "Reaction rate",
        "تصدير متقدم" to "Advanced export",
        "الجمهور" to "Audience",
        "إعجاز علمي" to "Scientific miracle",
        "3. ممنوع الإساءة للإسلام أو الرموز الدينية." to "3. It is forbidden to insult Islam or religious symbols.",
        "لا يوجد" to "nothing",
        "تجميع احترافي: templateInfo.name..." to "Professional compilation: templateInfo.name...",
        "ضوابط استوديو قبس" to "jack studio controls",
        "دعم HDR10+" to "HDR10+ support",
        "عالي (30 Mbps)" to "High (30Mbps)",
        "سرعة الانتقالات (بطيء إلى سريع)" to "Transition speed (slow to fast)",
        "مدينة" to "city",
        "ملخص الرؤية" to "Vision summary",
        "درامي" to "Dramatic",
        "سريع (Fast Cut)" to "Fast Cut",
        "العودة" to "Return",
        "تعديل مفاتيح API" to "Modify API keys",
        "الإصدار: 1.0.0" to "Version: 1.0.0",
        "احترافية" to "Professionalism",
        "التباين" to "Contrast",
        "إضافة دعوة متحركة (متابعة/مشاركة) في نهاية الفيديو." to "Add an animated invitation (follow/share) at the end of the video.",
        "مطر ورعد" to "Rain and thunder",
        "لا توجد مشاريع سابقة" to "There are no previous projects",
        "2. ممنوع تماماً أي محتوى جنسي أو ألفاظ بذيئة." to "2. Any sexual content or obscene language is strictly prohibited.",
        "عزف" to "play",
        "نموذج الذكاء الاصطناعي (إذا كان متاحاً)" to "AI model (if available)",
        "إضافة صوت" to "Add sound",
        "نحلل الكلمات لنرسم مشاهد إبداعية تليق برسالتك" to "We analyze words to draw creative scenes that suit your message",
        "فيديو" to "video",
        "جاري كتابة السيناريو..." to "Script is being written...",
        "مشروع " to "project",
        "كتابة" to "writing",
        "تلقائي" to "automatic",
        "استوديو قبس برو" to "Qabas Pro Studio",
        "المعالجة المتوازية" to "Parallel processing",
        "مشهد currentSceneIndex + 1 من currentScenes.size" to "Mashhad currentSceneIndex + 1 I currentScenes.size",
        "ذهبي" to "golden",
        "تعديل" to "amendment",
        "التشبع" to "Saturation",
        "قص" to "He told",
        "إباحي" to "pornographic",
        "المشاهد المقترحة" to "Suggested scenes",
        "جودة الريندر (Render Quality)" to "Render Quality",
        "معالجة متوازية: تم إنجاز \\scenesProcessed من \\totalScenes" to "Parallel processing: \\scenesProcessed from \\totalScenes",
        "خطاف تسويقي 2" to "Marketing hook 2",
        "اختر المؤثر الصوتي" to "Choose the sound effect",
        "الموافقة على الفيديو (الانتقال للدفع)" to "Video approval (proceed to payment)",
        "مخصص" to "Custom",
        "الترخيص: Qabas Studio License" to "License: Qabas Studio License",
        "قالب المونتاج" to "Montage template",
        "الكتابة" to "Writing",
        "وعي (Awareness)" to "Awareness",
        "مفاتيح API" to "API keys",
        "المدة" to "Duration",
        "متغير (A) - خطاف 1" to "Variant (A) - Hook 1",
        "تغيير المؤثر الصوتي المحيطي (\\ambientSound)" to "Change the ambient sound effect (\\ambientSound)",
        "مشرق" to "East",
        "الأسلوب الفني:" to "Artistic style:",
        "سينمائي داكن" to "Dark cinematic",
        "حدث خطأ أثناء الاتصال ببوابة الدفع." to "An error occurred while connecting to the payment gateway.",
        "[INFO] تخصيص الذاكرة: 8GB VRAM" to "[INFO] Memory Allocation: 8GB VRAM",
        "مسودة" to "draft",
        "عشوائي" to "random",
        "سريع" to "fast",
        "قالب المونتاج (Template):" to "Montage template:",
        "حدث خطأ أثناء المعالجة." to "An error occurred during processing.",
        "جاري عمل الريندر للفريمات... \\i%" to "Rendering for frames is in progress... \\i%",
        "مدفوع" to "feces",
        "إعادة" to "re",
        "موسيقى" to "music",
        "عريض" to "broad",
        "حركة النصوص" to "Text movement",
        "تكلفة الإنتاج" to "Production cost",
        "فكاهي سريع" to "Quick comic",
        "أسلوب 3nvus / نيون داكن" to "3nvus style/dark neon",
        "إعدادات الإنتاج" to "Production settings",
        "إعدادات التسويق (Marketing)" to "Marketing settings",
        "أغنية" to "song",
        "تشغيل" to "employment",
        "استيراد أسلوب إخراجي" to "Import output style",
        "هل فكرت يوماً أن وقتك أغلى من الذهب؟ شاهد لتفهم..." to "Have you ever thought that your time is more valuable than gold? Watch to understand...",
        "تفاعل (Engagement)" to "Engagement",
        "لا يمكن إخراج مشهد من الفراغ! اكتب شيئاً أولاً." to "A scene cannot be created out of thin air! Write something first.",
        "مشاريعي" to "My projects",
        "تنسيق العرض (Layout & Format)" to "Display format (Layout & Format)",
        "إعدادات الاستوديو المتقدمة" to "Advanced studio settings",
        "حفظ المشروع" to "Save the project",
        "عرض الكل" to "View all",
        "توقف عن التمرير! هذه الدقيقة ستغير حياتك..." to "Stop scrolling! This minute will change your life...",
        "النصوص" to "Texts",
        "الدفع والاستكمال" to "Payment and completion",
        "الكلمات المفتاحية" to "Keywords",
        "ألصق رابط يوتيوب أو تيك توك، وسيقوم الذكاء الاصطناعي بتحليل الألوان، الانتقالات، والإيقاع لتطبيقه على مشروعك." to "Paste a YouTube or TikTok link, and the AI ​​will analyze the colors, transitions, and rhythm to apply it to your project.",
        "المتابعة للإعدادات" to "Proceed to settings",
        "أحدث المشاريع" to "Latest projects",
        "تصدير" to "export",
        "خيارات الذكاء" to "Intelligence options",
        "محرك التصدير السينمائي" to "Film export engine",
        "المؤثرات الصوتية المحيطة" to "Ambient sound effects",
        "نهاية" to "end",
        "إذا تم إيقافه، سيتم استخدام وضع المحاكاة" to "If it is stopped, simulation mode will be used",
        "الدقة" to "Accuracy",
        "تحدي" to "challenge",
        "توثيق API" to "API documentation",
        "جاري تحضير التعديلات..." to "Edits are being prepared...",
        "إساءة للأنبياء" to "An insult to the prophets",
        "إيقاع حماسي (Daff)" to "Daff",
        "تم تغيير اللغة." to "The language has been changed.",
        "متوسط" to "average",
        "لوحة أداء التسويق" to "Marketing performance dashboard",
        "تم تطبيق التعديلات للمعاينة" to "Modifications have been applied for preview",
        "3 دقائق (يوتيوب)" to "3 minutes (YouTube)",
        "احترافية (Runway)" to "Professional (Runway)",
        "نجاح" to "success",
        "جودة التوليد" to "Obstetric quality",
        "جنس" to "sex",
        "نستلهم الأفكار..." to "We get inspired...",
        "وضعية المعاينة الفورية" to "Instant preview mode",
        "التمثيل الصوتي" to "Voice acting",
        "المؤثرات الصوتية" to "Sound effects",
        "ألصق رابط يوتيوب أو تيك توك" to "Paste the YouTube or TikTok link",
        "الوقت المتبقي تقريباً: \\estimatedTime ثانية" to "Approximate time remaining: \\estimatedTime seconds",
        "أدوات \\activeTool سيتم توفيرها قريباً..." to "\\activeTools will be available soon...",
        "مؤثرات" to "Influences",
        "اللغة" to "the language",
        "تم حفظ المشروع بنجاح" to "The project was saved successfully",
        "مرحباً بك في استوديو قبس. هذا التطبيق يلتزم بالضوابط التالية:" to "Welcome to Qabas Studio. This application adheres to the following controls:",
        "ماذا سنصنع اليوم؟ اختر مسار الإنتاج الخاص بك." to "What will we do today? Choose your production path.",
        "كيف تتخلص من القلق بمنظور إسلامي..." to "How to get rid of anxiety from an Islamic perspective...",
        "نشر مباشر" to "Live posting",
        "بدء المعالجة السينمائية" to "Start film processing",
        "وثائقي" to "documentary",
        "دعوة لاتخاذ إجراء (CTA)" to "Call to action (CTA)",
        "أصوات مسجد / جموع" to "Mosque/crowd sounds",
        "خطاف فيروسي" to "Viral hook",
        "ملحمية" to "Epic",
        "دع الذكاء يكمل الناقص" to "Let intelligence fill in what is lacking",
        "ملخص الإنتاج" to "Production summary",
        "ابدأ مشروعك السينمائي الأول الآن" to "Start your first film project now",
        "اختر إعدادات التصدير الاحترافية للفيديو:" to "Choose professional video export settings:",
        "جاري كتابة السيناريو بأسلوب مخصص..." to "The script is being written in a custom style...",
        "صوت المعلق (Voice Over):" to "Voice Over:",
        "إساءة للدين" to "Abuse of religion",
        "الخلفية الصوتية (BGM):" to "Background audio (BGM):",
        "اختر قالب المونتاج" to "Choose a montage template",
        "يستخدم فقط الموارد التي رفعتها" to "It only uses the resources you uploaded",
        "استخدم مواردي فقط" to "Use only my resources",
        "زوم وديناميكي" to "Zoom and dynamic",
        "تأكيد الدفع والاستكمال" to "Confirm payment and completion",
        "القالب الافتراضي" to "Default template",
        "المنصة المستهدفة:" to "Target platform:",
        "[SUCCESS] تم دمج الصوت وتصدير الملف بدقة 4K." to "[SUCCESS] Audio merged and file exported in 4K.",
        "قياسية (1080p HD)" to "Standard (1080p HD)",
        "احترافية (4K Cinematic)" to "Professional (4K Cinematic)",
        "تم التعديل حديثاً" to "Recently modified",
        "عالي" to "High",
        "مشاهد مولدة: " to "Generated scenes:",
        "خطأ" to "mistake",
        "هادئ" to "calm",
        "ملحمية إسلامية" to "Islamic epic",
        "1:1 (انستجرام)" to "1:1 (Instagram)",
        "اهتزاز" to "vibration",
        "قوالب النصوص و 3D" to "Text and 3D templates",
        "افتراضي" to "hypothetical",
        "جاري التجميع النهائي (FFmpeg)..." to "Final compilation (FFmpeg) in progress...",
        "جاري معالجة \\totalScenes مشاهد..." to "Processing \\totalScenes...",
        "تحرير متقدم" to "Advanced editing",
        "مؤثرات بصرية وانتقالات" to "Visual effects and transitions",
        "اكتملت المعالجة بنجاح!" to "Processing completed successfully!",
        "مستند" to "Documentary",
        "أدوات تسويقية" to "Marketing tools",
        "تفاصيل" to "details",
        "الافتتاحية المقترحة (Hooks)" to "Suggested opening (Hooks)",
        "مكتبة الأفكار الجاهزة" to "Library of ready-made ideas",
        "سيرة نبوية" to "Prophetic biography",
        "دعوة 1" to "Invitation 1",
        "النسخة الأساسية" to "Basic version",
        "التكلفة الإجمالية: \\" to "Total cost: \\",
        "فشلت عملية الدفع لشحن الرصيد." to "The payment process failed to top up the balance.",
        "الإطارات" to "Tires",
        "تم التقاط الأسلوب البصري" to "The visual style was captured",
        "حفظ للجهاز" to "Save to device",
        "حفظ التخصيص" to "Save customization",
        "التكلفة الإجمالية: \\totalCost\\" to "Total cost: \\totalCost\\",
        "عميق ووقور" to "deep and dignified",
        "معالجة تسلسلية: تم إنجاز \\scenesProcessed من \\totalScenes" to "Sequential processing: \\scenesProcessed from \\totalScenes",
        "داكن سينمائي" to "Cinematic dark",
        "تم التقاط الأسلوب البصري بنجاح!" to "The visual style was captured successfully!",
        "أسلوب المونتاج" to "Montage style",
        "تزكية النفس" to "Self-purification",
        "9:16 (ريلز/تيك توك)" to "9:16 (Reels/TikTok)",
        "جاري تحليل الإيقاع والألوان..." to "Analyzing rhythm and colors...",
        "الهوية البصرية (Visual Identity)" to "Visual Identity",
        "وسائطي" to "medium",
        "اقتباس أسلوب مخرج:" to "Exit style quote:",
        "معاينة وتعديل الفيديو" to "Preview and edit video",
        "30 ثانية" to "30 seconds",
        "تجميع المشاهد..." to "Scene collection...",
        "ملحمي وحماسي" to "Epic and epic",
        "معدل الإطارات" to "Frame rate",
        "جاري المعاينة الفورية..." to "Instant preview...",
        "وضع التشغيل" to "Operating mode",
        "إساءة للإسلام" to "An insult to Islam",
        "أصول الوسائط (Media Assets)" to "Media Assets",
        "رئاسي" to "presidential",
        "التحويلات (Leads)" to "Transfers (Leads)",
        "لعن" to "curse",
        "إساءة للذات الإلهية" to "An insult to God",
        "مشاهد من المكتبة: " to "Scenes from the library:",
        "أسود وذهبي" to "Black and gold",
        "60 ثانية" to "60 seconds",
        "تحليل الأسلوب" to "Style analysis",
        "العربية" to "Arabic",
        "تغيير المؤثر الصوتي" to "Change the sound effect",
        "غير محدد" to "undefined",
        "حساس" to "sensitive",
        "يحسن الأداء لكنه يستهلك طاقة أكبر" to "It improves performance but consumes more power",
        "مينيمال (بسيط ونظيف)" to "Minimal (simple and clean)",
        "التنسيق" to "Coordination",
        "خيارات الدفع" to "Payment options",
        "ملء الشاشة" to "Full screen",
        "رجوع" to "Reference",
        "تحفيز" to "incentivize",
        "اكتمل التصدير بنجاح!" to "Export completed successfully!",
        "إضافة Keyframe" to "Add Keyframe",
        "طيور وطبيعة" to "Birds and nature",
        "تعديل الرابط" to "Edit link",
        "إسلامي تراثي (زخارف)" to "Islamic heritage (ornaments)",
        "توقعات الأداء (Viral Predictor)" to "Performance Prediction (Viral Predictor)",
        "مشهد i+1" to "Mashhad i+1",
        "بطيء ومؤثر" to "Slow and poignant",
        "عميق" to "deep",
        "توليد نسختين لخطاف البداية لتحليل الأفضل أداءً." to "Generate two versions of the starting hook to analyze which performs best.",
        "تأملي عميق" to "Deep contemplation",
        "الرجاء رفع موارد أولاً" to "Please upload resources first",
        "الأبعاد" to "Dimensions",
        "المشاريع" to "Projects",
        "تعديل النصوص" to "Edit texts",
        "جاري التحضير..." to "Preparing...",
        "تعديل النمط" to "Edit style",
        "تعديل الألوان الاحترافي (LUTs)" to "Professional color tuning (LUTs)",
        "استخدام APIs حقيقية" to "Use real APIs",
        "بناء المشاهد (0%)" to "Building scenes (0%)",
        "خاتمة" to "conclusion",
        "مكتمل" to "complete",
        "تكلفة الجودة الاحترافية: +\\" to "Cost of professional quality: +\\",
        "جمع الموارد والإعدادات" to "Gather resources and settings",
        "15 ثانية" to "15 seconds",
        "تم شحن الرصيد بنجاح!" to "The balance has been charged successfully!",
        "تغيير قالب المونتاج (\\selectedTemplate)" to "Change the montage template (\\selectedTemplate)",
        "الرسوم المتحركة (Keyframes)" to "Animation (Keyframes)",
        "حول التطبيق" to "About the application",
        "رصيدك غير كافٍ. الرجاء اختيار بطاقة شحن." to "Your balance is insufficient. Please choose a shipping card.",
        "رفع صورة" to "Upload a photo",
        "إيقاف مؤقت" to "Pause",
        "خطاف 1" to "Hook 1",
        "نبرة المحتوى" to "Tone of content",
        "نصوص" to "Texts",
        "عاري" to "Naked",
        "أسلوب analysis.dominantColors، انتقالات analysis.transitionSpeed، الإيقاع: analysis.overallRhythm، الصوت: analysis.audioStyle، الخط: analysis.typographyStyle" to "Style analysis.dominantColors, transitions analysis.transitionSpeed, tempo: analysis.overallRhythm, audio: analysis.audioStyle, font: analysis.typographyStyle",
        "الفيديو" to "video",
        "صوتيات" to "phonetics",
        "صوت" to "voice",
        "الرئيسية" to "Home",
        "1. لا تُستخدم الموسيقى، بل مؤثرات صوتية مباحة." to "1. Music is not used, only permissible sound effects.",
        "سريع Reels" to "Fast Reels",
        "قفز" to "jump",
        "تحويل الفكرة إلى مشهد" to "Turning an idea into a scene",
        "شاب وحماسي" to "Young and enthusiastic",
        "الهدف التسويقي:" to "Marketing objective:",
        "دمج الصوت المحيطي: \\ambientSound..." to "Surround sound integration: \\ambientSound...",
        "لم يتم توليد أي مشاهد." to "No scenes generated.",
        "مقدمة" to "introduction",
        "عذراً، الفكرة تحتوي على محتوى غير لائق أو مخالف لضوابط التطبيق." to "Sorry, the idea contains inappropriate content or violates the application's controls.",
        "خطاف تسويقي 1" to "Marketing hook 1",
        "أهلاً بك في استوديو الإنتاج 🎬" to "Welcome to the production studio 🎬",
        "داكن" to "dark",
        "لا يوجد اتصال بالإنترنت. تم تفعيل وضع عدم الاتصال." to "No internet connection. Offline mode is activated.",
        "قصة تاريخية" to "Historical story",
        "متابعة للمزيد" to "Follow for more",
        "استوديو قبس" to "Qabas Studio",
        "عدد المشاهد المولدة: \\generatedScenesCount" to "Number of generated scenes: \\generatedScenesCount",
        "بدون" to "without",
        "سينمائي" to "cinematographic",
        "يبحث ويولد المكملات" to "Searches and generates supplements",
        "احترافية (Runway Gen-2 / Pika Labs)" to "Professional (Runway Gen-2 / Pika Labs)",
        "شتم" to "Shatm",
        "اكتب فكرتك الإبداعية هنا...\\nمثال: قصة نجاح ملهمة عن شاب بدأ من الصفر وحقق حلمه بفضل الإصرار." to "Write your creative idea here...\\nExample: An inspiring success story about a young man who started from scratch and achieved his dream thanks to persistence.",
        "[WARN] تطبيق فلاتر Color Grading للطبقة i/25..." to "[WARN] Apply Color Grading filters to layer i/25...",
        "إلغاء" to "cancellation",
        "هندسة الصوت (Audio Engineering)" to "Audio Engineering",
        "بداية" to "beginning",
        "رفع فيديو" to "Upload a video",
        "إيقاع" to "rhythm",
        "سرد وثائقي" to "Documentary narrative",
        "تعديل الألوان" to "Adjust colors",
        "الأسلوب المقترح: " to "Suggested method:",
        "قالب i+1" to "format i+1",
        "تخصيص القالب" to "Customize the template",
        "عالية (4K Cinematic)" to "High (4K Cinematic)",
        "معاينة سريعة" to "Quick preview",
        "تأملات في الكون تثبت عظمة الخالق..." to "Reflections on the universe prove the greatness of the Creator...",
        "طبيعة" to "nature",
        "الموقع: www.qabas.studio" to "Website: www.qabas.studio",
        "الشباب" to "Youth",
    )
    
    fun tr(text: String): String {
        if (currentLanguage == "ar") return text
        return dictionaryEn[text] ?: text
    }
}
