package com.example

import androidx.compose.animation.*
import androidx.compose.animation.core.tween
import androidx.compose.foundation.*
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyRow
import androidx.compose.foundation.lazy.itemsIndexed
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.material3.TabRowDefaults.tabIndicatorOffset
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.draw.shadow
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.graphicsLayer
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import coil.compose.AsyncImage
import coil.request.ImageRequest
import coil.size.Size
import com.example.ui.theme.*
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun ReviewScreen(
    state: ProjectState = ProjectState(),
    onBack: () -> Unit,
    onUpdateScenes: (List<Scene>) -> Unit = {},
    onUpdateAmbientSound: (String) -> Unit = {},
    onAdvancedEdit: () -> Unit,
    onApprove: () -> Unit
) {
    val context = LocalContext.current
    val snackbarHostState = remember { SnackbarHostState() }
    val scope = rememberCoroutineScope()
    
    // State
    var selectedVariant by remember { mutableStateOf("النسخة المولدة بالذكاء الاصطناعي") }
    var playbackProgress by remember { mutableFloatStateOf(0f) }
    var currentSceneIndex by remember { mutableIntStateOf(0) }
    var isPlaying by remember { mutableStateOf(false) }
    var isPreviewModeActive by remember { mutableStateOf(false) }
    var showTemplateDialog by remember { mutableStateOf(false) }
    var showAmbientDialog by remember { mutableStateOf(false) }
    var selectedTemplate by remember { mutableStateOf("الافتراضي") }
    var ambientSound by remember(state.ambientSound) { mutableStateOf(state.ambientSound.ifBlank { "بدون" }) }
    var isFullScreen by remember { mutableStateOf(false) }
    var sceneForBRollModal by remember { mutableStateOf<Scene?>(null) }

    // Use real scenes generated by Gemini
    val realScenes: List<Scene> = remember(state.scenesToProcess, state.libraryScenes) {
        state.scenesToProcess?.takeIf { it.isNotEmpty() } ?: state.libraryScenes
    }
    
    val scenesByVariant = remember(realScenes) {
        mapOf(
            "النسخة المولدة بالذكاء الاصطناعي" to realScenes
        )
    }
    
    val currentScenes = remember(scenesByVariant, selectedVariant) {
        scenesByVariant[selectedVariant] ?: emptyList()
    }
    val totalDuration by remember(currentScenes) {
        derivedStateOf { currentScenes.sumOf { it.durationInSeconds }.toFloat() }
    }

    // Playback loop
    LaunchedEffect(isPlaying, selectedVariant) {
        if (isPlaying) {
            while (playbackProgress < totalDuration) {
                delay(100)
                playbackProgress += 0.1f
                
                // Update current scene based on progress
                var accumulated = 0f
                for ((index, scene) in currentScenes.withIndex()) {
                    accumulated += scene.durationInSeconds
                    if (playbackProgress <= accumulated) {
                        currentSceneIndex = index
                        break
                    }
                }
            }
            isPlaying = false
            playbackProgress = 0f
            currentSceneIndex = 0
        }
    }

    Scaffold(
        snackbarHost = { SnackbarHost(snackbarHostState) },
        containerColor = DeepSlate,
        topBar = {
            TopAppBar(
                title = { 
                    Text(
                        Translator.tr("عرض النتيجة"), 
                        fontFamily = CairoFont, 
                        fontWeight = FontWeight.Bold, 
                        color = GoldPrimary, 
                        fontSize = 20.sp
                    ) 
                },
                navigationIcon = {
                    IconButton(onClick = onBack) {
                        Icon(Icons.AutoMirrored.Filled.ArrowBack, contentDescription = Translator.tr("العودة"), tint = GoldPrimary)
                    }
                },
                actions = {
                    IconButton(onClick = onAdvancedEdit) {
                        Icon(Icons.Default.Tune, contentDescription = Translator.tr("تعديل متقدم"), tint = GoldPrimary)
                    }
                },
                colors = TopAppBarDefaults.topAppBarColors(containerColor = DeepSlate)
            )
        }
    ) { paddingValues ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(paddingValues)
                .verticalScroll(rememberScrollState()),
            verticalArrangement = Arrangement.spacedBy(24.dp)
        ) {
            
            if (showTemplateDialog) {
                LiveTemplateCustomizerDialog(
                    currentTemplateName = selectedTemplate,
                    onDismiss = { showTemplateDialog = false },
                    onApplyTemplate = { tmpl, transition, speed ->
                        selectedTemplate = tmpl.name
                        showTemplateDialog = false
                        scope.launch {
                            snackbarHostState.showSnackbar("تم تطبيق قالب: ${tmpl.name} مع انتقال $transition بسرعة $speed ثانية ✦")
                        }
                    }
                )
            }

            sceneForBRollModal?.let { scene ->
                BRollSelectionModal(
                    sceneTitle = scene.title,
                    currentMediaUrl = scene.mediaUrl,
                    onDismiss = { sceneForBRollModal = null },
                    onSelectBRoll = { brollItem ->
                        val updatedScenes = currentScenes.map { 
                            if (it.title == scene.title) it.copy(mediaUrl = brollItem.videoUrl.ifBlank { brollItem.thumbnailUrl }, transitionType = brollItem.suggestedTransition) else it 
                        }
                        onUpdateScenes(updatedScenes)
                        sceneForBRollModal = null
                        scope.launch {
                            snackbarHostState.showSnackbar("تم إرفاق B-Roll الذكي: ${brollItem.title} 🎬")
                        }
                    }
                )
            }

            if (showAmbientDialog) {
                AlertDialog(
                    onDismissRequest = { showAmbientDialog = false },
                    title = { Text(Translator.tr("الصوت المحيطي"), fontFamily = CairoFont, color = GoldPrimary) },
                    text = {
                        Column {
                            listOf("بدون", "طبيعة وهدوء", "أجواء سينمائية", "نشاط وحيوية").forEach { sound ->
                                TextButton(
                                    onClick = { 
                                        ambientSound = sound
                                        onUpdateAmbientSound(sound)
                                        showAmbientDialog = false
                                        scope.launch {
                                            snackbarHostState.showSnackbar(Translator.tr("تم تغيير الصوت إلى") + " " + sound)
                                        }
                                    },
                                    modifier = Modifier.fillMaxWidth()
                                ) {
                                    Text(sound, color = if (ambientSound == sound) GoldPrimary else TextPrimary, fontFamily = CairoFont)
                                }
                            }
                        }
                    },
                    confirmButton = {
                        TextButton(onClick = { showAmbientDialog = false }) {
                            Text(Translator.tr("إلغاء"), color = TextSecondary, fontFamily = CairoFont)
                        }
                    },
                    containerColor = CardSurface
                )
            }

            // Variants Tabs
            ScrollableTabRow(
                selectedTabIndex = scenesByVariant.keys.indexOf(selectedVariant).coerceAtLeast(0),
                containerColor = Color.Transparent,
                edgePadding = 16.dp,
                divider = {},
                indicator = { tabPositions ->
                    TabRowDefaults.SecondaryIndicator(
                        modifier = Modifier.tabIndicatorOffset(tabPositions[scenesByVariant.keys.indexOf(selectedVariant).coerceAtLeast(0)]),
                        color = GoldPrimary,
                        height = 3.dp
                    )
                }
            ) {
                scenesByVariant.keys.forEach { title ->
                    Tab(
                        selected = selectedVariant == title,
                        onClick = { 
                            selectedVariant = title 
                            playbackProgress = 0f
                            currentSceneIndex = 0
                            isPlaying = false
                        },
                        text = { 
                            Text(
                                title, 
                                color = if (selectedVariant == title) GoldPrimary else TextSecondary, 
                                fontFamily = CairoFont, 
                                fontWeight = FontWeight.Bold,
                                fontSize = 16.sp
                            ) 
                        },
                        modifier = Modifier.padding(bottom = 8.dp)
                    )
                }
            }

            // Video Player Area
            VideoPlayerView(
                scenes = currentScenes,
                currentSceneIndex = currentSceneIndex,
                playbackProgress = playbackProgress,
                totalDuration = totalDuration,
                isPlaying = isPlaying,
                onPlayPause = { isPlaying = !isPlaying },
                onSeek = { 
                    playbackProgress = it
                    var acc = 0f
                    for ((i, s) in currentScenes.withIndex()) {
                        acc += s.durationInSeconds
                        if (playbackProgress <= acc) {
                            currentSceneIndex = i
                            break
                        }
                    }
                },
                onFullScreen = { isFullScreen = !isFullScreen }
            )

            // Timeline / Scenes thumbnails
            ScenesTimeline(
                scenes = currentScenes,
                currentIndex = currentSceneIndex,
                onSceneSelected = { index ->
                    currentSceneIndex = index
                    playbackProgress = currentScenes.take(index).sumOf { it.durationInSeconds }.toFloat()
                }
            )

            currentScenes.getOrNull(currentSceneIndex)?.let { currentScene ->
                Column(modifier = Modifier.padding(horizontal = 20.dp)) {
                    SceneBRollAndTransitionBadge(
                        sceneIndex = currentSceneIndex,
                        transitionType = currentScene.transitionType,
                        mediaUrl = currentScene.mediaUrl,
                        onOpenBRollSelector = { sceneForBRollModal = currentScene }
                    )
                }
            }

            // Feedback & Analytics
            TasteFeedbackSection(
                onLike = {
                    scope.launch {
                        val activeStyleName = state.editingStyle.ifBlank { selectedVariant }
                        StyleBrain.recordUserFeedbackOnStyle(
                            context = context,
                            styleVariantOrName = activeStyleName,
                            isPositive = true
                        )
                        snackbarHostState.showSnackbar(Translator.tr("شكراً لتقييمك! تم تعزيز وتطوير عقل قبس الإخراجي."))
                    }
                },
                onDislike = {
                    scope.launch {
                        val activeStyleName = state.editingStyle.ifBlank { selectedVariant }
                        StyleBrain.recordUserFeedbackOnStyle(
                            context = context,
                            styleVariantOrName = activeStyleName,
                            isPositive = false
                        )
                        snackbarHostState.showSnackbar(Translator.tr("تم تسجيل ملاحظتك وتعديل موازين العقل الإخراجي."))
                    }
                }
            )

            // Action Buttons
            Column(
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(horizontal = 20.dp, vertical = 16.dp),
                verticalArrangement = Arrangement.spacedBy(16.dp)
            ) {
                // Secondary actions
                Row(
                    modifier = Modifier.fillMaxWidth(),
                    horizontalArrangement = Arrangement.spacedBy(12.dp)
                ) {
                    OutlinedButton(
                        onClick = { showTemplateDialog = true },
                        modifier = Modifier
                            .weight(1f)
                            .height(52.dp),
                        colors = ButtonDefaults.outlinedButtonColors(contentColor = GoldPrimary),
                        border = BorderStroke(1.dp, GoldPrimary.copy(alpha = 0.5f)),
                        shape = RoundedCornerShape(14.dp)
                    ) {
                        Icon(Icons.Default.Palette, contentDescription = null, modifier = Modifier.size(20.dp))
                        Spacer(modifier = Modifier.width(8.dp))
                        Text(Translator.tr("القالب"), fontFamily = CairoFont, fontWeight = FontWeight.SemiBold)
                    }

                    OutlinedButton(
                        onClick = { showAmbientDialog = true },
                        modifier = Modifier
                            .weight(1f)
                            .height(52.dp),
                        colors = ButtonDefaults.outlinedButtonColors(contentColor = GoldPrimary),
                        border = BorderStroke(1.dp, GoldPrimary.copy(alpha = 0.5f)),
                        shape = RoundedCornerShape(14.dp)
                    ) {
                        Icon(Icons.Default.GraphicEq, contentDescription = null, modifier = Modifier.size(20.dp))
                        Spacer(modifier = Modifier.width(8.dp))
                        Text(Translator.tr("الصوت"), fontFamily = CairoFont, fontWeight = FontWeight.SemiBold)
                    }
                }

                // Primary Action - Export / Approve
                Button(
                    onClick = onApprove,
                    modifier = Modifier
                        .fillMaxWidth()
                        .height(60.dp)
                        .shadow(8.dp, RoundedCornerShape(16.dp), spotColor = GoldPrimary),
                    colors = ButtonDefaults.buttonColors(containerColor = Color.Transparent),
                    contentPadding = PaddingValues(0.dp),
                    shape = RoundedCornerShape(16.dp)
                ) {
                    val goldGradient = Brush.horizontalGradient(listOf(GoldSecondary, GoldPrimary))
                    Box(
                        modifier = Modifier
                            .fillMaxSize()
                            .background(goldGradient),
                        contentAlignment = Alignment.Center
                    ) {
                        Row(verticalAlignment = Alignment.CenterVertically) {
                            Icon(Icons.Default.Download, contentDescription = null, tint = DeepSlate)
                            Spacer(modifier = Modifier.width(8.dp))
                            Text(
                                Translator.tr("حفظ وتصدير الفيديو"), 
                                color = DeepSlate, 
                                fontFamily = CairoFont, 
                                fontWeight = FontWeight.Bold, 
                                fontSize = 18.sp
                            )
                        }
                    }
                }
            }
        }
    }
}

@Composable
fun VideoPlayerView(
    scenes: List<Scene>,
    currentSceneIndex: Int,
    playbackProgress: Float,
    totalDuration: Float,
    isPlaying: Boolean,
    onPlayPause: () -> Unit,
    onSeek: (Float) -> Unit,
    onFullScreen: () -> Unit
) {
    val activeScene = scenes.getOrNull(currentSceneIndex)
    
    Box(
        modifier = Modifier
            .fillMaxWidth()
            .padding(horizontal = 20.dp)
            .aspectRatio(16f / 9f)
            .clip(RoundedCornerShape(16.dp))
            .background(Color.Black)
            .border(2.dp, GoldPrimary.copy(alpha = 0.5f), RoundedCornerShape(16.dp))
    ) {
        if (activeScene != null) {
            AnimatedContent(
                targetState = activeScene,
                transitionSpec = {
                    fadeIn(tween(500)) togetherWith fadeOut(tween(500))
                },
                label = "scene_transition"
            ) { scene ->
                Box(modifier = Modifier.fillMaxSize()) {
                    AsyncImage(
                        model = ImageRequest.Builder(LocalContext.current)
                            .data(scene.mediaUrl)
                            .crossfade(true)
                            .size(Size.ORIGINAL)
                            .build(),
                        contentDescription = "Scene Background",
                        modifier = Modifier
                            .fillMaxSize()
                            .graphicsLayer { alpha = 0.8f },
                        contentScale = ContentScale.Crop
                    )
                    
                    // Gradient overlay for better text readability
                    Box(
                        modifier = Modifier
                            .fillMaxSize()
                            .background(
                                Brush.verticalGradient(
                                    colors = listOf(Color.Transparent, Color.Black.copy(alpha = 0.8f)),
                                    startY = 100f
                                )
                            )
                    )

                    // Subtitles / Scene Text
                    Column(
                        modifier = Modifier
                            .align(Alignment.BottomCenter)
                            .padding(bottom = 60.dp, start = 24.dp, end = 24.dp),
                        horizontalAlignment = Alignment.CenterHorizontally
                    ) {
                        Text(
                            text = scene.title,
                            color = GoldPrimary,
                            fontSize = 18.sp,
                            fontFamily = CairoFont,
                            fontWeight = FontWeight.Bold,
                            textAlign = TextAlign.Center
                        )
                        if (scene.description.isNotBlank() && !scene.description.startsWith("Cinematic", ignoreCase = true) && !scene.description.startsWith("Close up", ignoreCase = true) && !scene.description.startsWith("Breathtaking", ignoreCase = true) && !scene.description.startsWith("Majestic", ignoreCase = true)) {
                            Spacer(modifier = Modifier.height(6.dp))
                            Text(
                                text = scene.description,
                                color = Color.White.copy(alpha = 0.9f),
                                fontSize = 13.sp,
                                fontFamily = CairoFont,
                                textAlign = TextAlign.Center
                            )
                        }
                        Spacer(modifier = Modifier.height(8.dp))
                        IslamicSourceAttributionBadge(
                            text = "${scene.title} ${scene.description}"
                        )
                    }
                }
            }
        }

        // Controls Overlay
        Box(
            modifier = Modifier
                .align(Alignment.BottomCenter)
                .fillMaxWidth()
                .background(Brush.verticalGradient(listOf(Color.Transparent, Color.Black.copy(alpha = 0.9f))))
                .padding(horizontal = 16.dp, vertical = 8.dp)
        ) {
            Column {
                // Seekbar
                Slider(
                    value = playbackProgress,
                    onValueChange = onSeek,
                    valueRange = 0f..(if (totalDuration > 0) totalDuration else 1f),
                    colors = SliderDefaults.colors(
                        thumbColor = GoldPrimary,
                        activeTrackColor = GoldPrimary,
                        inactiveTrackColor = Color.White.copy(alpha = 0.3f)
                    ),
                    modifier = Modifier
                        .fillMaxWidth()
                        .height(20.dp)
                )
                
                Row(
                    modifier = Modifier.fillMaxWidth(),
                    horizontalArrangement = Arrangement.SpaceBetween,
                    verticalAlignment = Alignment.CenterVertically
                ) {
                    // Time
                    Text(
                        text = String.format("%02d:%02d", (playbackProgress / 60).toInt(), (playbackProgress % 60).toInt()),
                        color = Color.White,
                        fontSize = 12.sp,
                        fontFamily = RobotoMonoFont
                    )
                    
                    // Play controls
                    Row(
                        horizontalArrangement = Arrangement.Center,
                        verticalAlignment = Alignment.CenterVertically
                    ) {
                        IconButton(
                            onClick = onPlayPause,
                            modifier = Modifier
                                .size(48.dp)
                                .clip(CircleShape)
                                .background(GoldPrimary.copy(alpha = 0.2f))
                        ) {
                            Icon(
                                imageVector = if (isPlaying) Icons.Default.Pause else Icons.Default.PlayArrow,
                                contentDescription = if (isPlaying) Translator.tr("إيقاف مؤقت") else Translator.tr("تشغيل"),
                                tint = GoldPrimary,
                                modifier = Modifier.size(28.dp)
                            )
                        }
                    }
                    
                    // Time total & Fullscreen
                    Row(verticalAlignment = Alignment.CenterVertically) {
                        Text(
                            text = String.format("%02d:%02d", (totalDuration / 60).toInt(), (totalDuration % 60).toInt()),
                            color = Color.White.copy(alpha = 0.7f),
                            fontSize = 12.sp,
                            fontFamily = RobotoMonoFont
                        )
                        IconButton(onClick = onFullScreen) {
                            Icon(Icons.Default.Fullscreen, contentDescription = Translator.tr("ملء الشاشة"), tint = Color.White)
                        }
                    }
                }
            }
        }
    }
}

@Composable
fun ScenesTimeline(
    scenes: List<Scene>,
    currentIndex: Int,
    onSceneSelected: (Int) -> Unit
) {
    Column(modifier = Modifier.fillMaxWidth()) {
        Text(
            text = Translator.tr("المشاهد (${scenes.size})"),
            color = TextPrimary,
            fontFamily = CairoFont,
            fontWeight = FontWeight.Bold,
            fontSize = 16.sp,
            modifier = Modifier.padding(horizontal = 20.dp)
        )
        Spacer(modifier = Modifier.height(12.dp))
        
        LazyRow(
            contentPadding = PaddingValues(horizontal = 20.dp),
            horizontalArrangement = Arrangement.spacedBy(12.dp)
        ) {
            itemsIndexed(scenes) { index, scene ->
                val isSelected = index == currentIndex
                Box(
                    modifier = Modifier
                        .width(120.dp)
                        .height(68.dp)
                        .clip(RoundedCornerShape(8.dp))
                        .border(
                            2.dp,
                            if (isSelected) GoldPrimary else Color.Transparent,
                            RoundedCornerShape(8.dp)
                        )
                        .clickable { onSceneSelected(index) }
                ) {
                    AsyncImage(
                        model = ImageRequest.Builder(LocalContext.current)
                            .data(scene.mediaUrl)
                            .crossfade(true)
                            .build(),
                        contentDescription = "Scene Thumbnail",
                        modifier = Modifier.fillMaxSize(),
                        contentScale = ContentScale.Crop
                    )
                    
                    if (!isSelected) {
                        Box(modifier = Modifier.fillMaxSize().background(Color.Black.copy(alpha = 0.5f)))
                    }
                    
                    // Duration badge
                    Box(
                        modifier = Modifier
                            .align(Alignment.BottomEnd)
                            .padding(4.dp)
                            .background(Color.Black.copy(alpha = 0.7f), RoundedCornerShape(4.dp))
                            .padding(horizontal = 4.dp, vertical = 2.dp)
                    ) {
                        Text(
                            text = "00:0${scene.durationInSeconds}",
                            color = Color.White,
                            fontSize = 10.sp,
                            fontFamily = RobotoMonoFont
                        )
                    }
                }
            }
        }
    }
}

@Composable
fun TasteFeedbackSection(
    onLike: () -> Unit,
    onDislike: () -> Unit
) {
    Card(
        modifier = Modifier
            .fillMaxWidth()
            .padding(horizontal = 20.dp),
        colors = CardDefaults.cardColors(containerColor = CardSurface),
        border = BorderStroke(1.dp, Color(0xFF1E293B)),
        shape = RoundedCornerShape(16.dp)
    ) {
        Column(
            modifier = Modifier.padding(16.dp),
            verticalArrangement = Arrangement.spacedBy(16.dp),
            horizontalAlignment = Alignment.CenterHorizontally
        ) {
            Row(
                verticalAlignment = Alignment.CenterVertically,
                horizontalArrangement = Arrangement.Center
            ) {
                Icon(Icons.Default.AutoAwesome, contentDescription = null, tint = GoldPrimary, modifier = Modifier.size(20.dp))
                Spacer(modifier = Modifier.width(8.dp))
                Text(
                    Translator.tr("ما رأيك في النتيجة؟"), 
                    color = TextPrimary, 
                    fontFamily = CairoFont, 
                    fontWeight = FontWeight.Bold,
                    fontSize = 16.sp
                )
            }
            
            Text(
                Translator.tr("تقييمك يساعد الذكاء الاصطناعي على فهم أسلوبك وتفضيلاتك للمشاريع القادمة."), 
                color = TextSecondary, 
                fontSize = 13.sp, 
                fontFamily = NotoSansFont, 
                textAlign = TextAlign.Center
            )
            
            Row(
                horizontalArrangement = Arrangement.spacedBy(16.dp),
                modifier = Modifier.fillMaxWidth()
            ) {
                OutlinedButton(
                    onClick = onLike,
                    modifier = Modifier
                        .weight(1f)
                        .height(48.dp),
                    colors = ButtonDefaults.outlinedButtonColors(contentColor = Color(0xFF22C55E)),
                    border = BorderStroke(1.dp, Color(0xFF22C55E).copy(alpha = 0.5f)),
                    shape = RoundedCornerShape(12.dp)
                ) {
                    Icon(Icons.Default.ThumbUp, contentDescription = null, modifier = Modifier.size(18.dp))
                    Spacer(modifier = Modifier.width(8.dp))
                    Text(Translator.tr("ممتاز"), fontFamily = CairoFont, fontWeight = FontWeight.Bold)
                }
                
                OutlinedButton(
                    onClick = onDislike,
                    modifier = Modifier
                        .weight(1f)
                        .height(48.dp),
                    colors = ButtonDefaults.outlinedButtonColors(contentColor = Color(0xFFEF4444)),
                    border = BorderStroke(1.dp, Color(0xFFEF4444).copy(alpha = 0.5f)),
                    shape = RoundedCornerShape(12.dp)
                ) {
                    Icon(Icons.Default.ThumbDown, contentDescription = null, modifier = Modifier.size(18.dp))
                    Spacer(modifier = Modifier.width(8.dp))
                    Text(Translator.tr("يحتاج تحسين"), fontFamily = CairoFont, fontWeight = FontWeight.Bold)
                }
            }
        }
    }
}
